# Generated by Django 3.2.7 on 2021-10-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20211002_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critic',
            name='critic_question',
            field=models.FileField(default='static/def/check.docx', upload_to='static/articles/'),
        ),
        migrations.AlterField(
            model_name='subs',
            name='subscriber_Name',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
