# Generated by Django 3.2.7 on 2021-10-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20211002_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critic',
            name='critic_question',
            field=models.TextField(),
        ),
    ]
