# Generated by Django 3.2.7 on 2021-10-04 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_critic_critic_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subs',
        ),
    ]
