# Generated by Django 3.2.7 on 2021-10-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0003_auto_20211002_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='develop',
            name='writer_name',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
