# Generated by Django 3.2.7 on 2021-10-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0004_alter_develop_writer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='develop',
            name='article_img',
            field=models.ImageField(default='static/artimage/123.jpg', upload_to=''),
        ),
    ]
