# Generated by Django 3.2.7 on 2021-10-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0005_develop_article_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='develop',
            name='article_category',
            field=models.CharField(choices=[('Psychology', 'PSY'), ('Educational Philosophy', 'EDU')], default='Psychology', max_length=50),
        ),
        migrations.AlterField(
            model_name='develop',
            name='article',
            field=models.FileField(default='static/articles/check.docx', upload_to='static/articles/'),
        ),
        migrations.AlterField(
            model_name='develop',
            name='article_img',
            field=models.ImageField(default='static/artimage/123.jpg', upload_to='static/artimage/'),
        ),
    ]
