# Generated by Django 3.2.7 on 2021-10-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0006_auto_20211003_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='develop',
            name='article_category',
            field=models.CharField(choices=[('PSY', 'Psychology'), ('EDU', 'Educational Philosophy')], default='Psychology', max_length=50),
        ),
    ]
