# Generated by Django 3.2.7 on 2021-10-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0007_alter_develop_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='develop',
            name='article',
        ),
        migrations.AddField(
            model_name='develop',
            name='para1',
            field=models.TextField(default='Para'),
        ),
        migrations.AddField(
            model_name='develop',
            name='para2',
            field=models.TextField(default='Para'),
        ),
        migrations.AddField(
            model_name='develop',
            name='para3',
            field=models.TextField(default='Para'),
        ),
        migrations.AddField(
            model_name='develop',
            name='para4',
            field=models.TextField(default='Para'),
        ),
        migrations.AddField(
            model_name='develop',
            name='para5',
            field=models.TextField(default='Para'),
        ),
        migrations.AddField(
            model_name='develop',
            name='para6',
            field=models.TextField(default='Para'),
        ),
    ]
